## Array Slicing

In [2]:
import numpy as np
a = np.array([1,8,9,9,6,5])
print(a[1:4:1]) # a[1:4] 

[8 9 9]


In [3]:
# slice element from index 3 to the end of array
import numpy as np
ar = np.array([1,8,9,2,8,8,5,2,4,7,5,6])
print(ar[3:])

[2 8 8 5 2 4 7 5 6]


In [4]:
# slice element from the beginning to index 7
import numpy as np
ar = np.array([1,8,9,2,8,8,5,2,4,7,5,6])
print(ar[:8])

[1 8 9 2 8 8 5 2]


### Negative Slicing

In [8]:
import numpy as np
a = np.array([1,8,9,1,8,2,6,9])
print(a[-4:-1]) # stop = n-1 

[8 2 6]


### Step

In [13]:
import numpy as np
a = np.array([1,8,9,3,8,9,6,9,2,5,3])
print(a[1:9:2])

[8 3 9 9]


### Return every other element from entire list

In [16]:
 import numpy as np
a = np.array([1,8,9,3,8,9,6,9,2,5,3])
print(a[::2])

[1 9 8 6 2 3]


### Reverse a list

In [15]:
import numpy as np
a = np.array([1,8,9,3,8,9,6,9,2,5,3])
print(a[::-1])

[3 5 2 9 6 9 8 3 9 8 1]


### 2-D Array Slicing
#### Syntax --- > a[element , start : stop : step ]

In [17]:
import numpy as np
a = np.array([[1,8,9,2,6,9],[8,9,6,4,7,2]])
print(a[1,1:4])

[9 6 4]


### From both elements,return value

In [22]:
import numpy as np 
a = np.array([[4,9,5,8,2,6],[8,9,2,1,4,5]])
print(a[0:2, 1:5])

[[9 5 8 2]
 [9 2 1 4]]
