## Array Copy vs View

## Copy

In [2]:
# Make a copy chnage the array and display both array
import numpy as np
ax = np.array([1,8,6,2,6])
x = ax.copy()
ax[0]=3
print(ax)
print(x)


[3 8 6 2 6]
[1 8 6 2 6]


In [11]:
# make changes in copy
import numpy as np
ax=np.array([1,4,8,5,6])
x=ax.copy()
x[2]=8
print(ax)
print(x)


[1 4 8 5 6]
[1 4 8 5 6]


## View

In [6]:
import numpy as np
ax = np.array([1,18,9,2,9])
x=ax.view()
ax[2]=33
print(ax)
print(x)

[ 1 18 33  2  9]
[ 1 18 33  2  9]


In [10]:
import numpy as np

ax=np.array([8,5,2,5,2,2,4,5])
x = ax.copy()
y = ax.view()

print(x.base)
print(y.base)

None
[8 5 2 5 2 2 4 5]
