## Dimensions In Array

In [1]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
arr =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
import numpy as np
a = np.array(1)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
e = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[11,12,13],[14,15,16]],[[17,18,19],[21,22,23]]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4


### Higher Dimensional Arrays

In [17]:
import numpy as np
arr=np.array([1,2,3,4], ndmin=15) # upto 32-D
arr
print('Number of dimensions ',arr.ndim)

Number of dimensions  15
