## Filter Array

In [2]:
import numpy as np
ax = np.array([41,42,43,44])
x=[True,False,True,False]
newarr = ax[x]
print(newarr)
# the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.



[41 43]


### Creating the filter array

In [8]:
import numpy as np
ax = np.array([41,42,43,44])
# create an empty list
filter_ar =[]
# go through each element in array
for element in ax:
    if element > 42:
      filter_ar.append(True)
    else : 
      filter_ar.append(False)
newarr = ax[filter_ar]
print(filter_ar)
print(ax)
    

[False, False, True, True]
[41 42 43 44]


Create a filter array that will return only even elements from the original array:

In [9]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7])
# create an empty list
fil_ar=[]
# go through each element in arr
for element in arr : 
    if element % 2 == 0:
      fil_ar.append(True)
    else:
      fil_ar.append(False)
newarr= arr[fil_ar]
print(fil_ar)
print(newarr)
        
        

[False, True, False, True, False, True, False]
[2 4 6]


Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to

In [10]:
# Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [11]:
# Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
