## Iterating Arrays

In [19]:
import numpy as np
ax= np.array([1,8,6,7,5,2,5,8,5])

for x in ax:
    print(x)

1
8
6
7
5
2
5
8
5


In [20]:
import numpy as np
ax = np.array([[1,2,3,4],[8,9,6,5]])
for x in ax:
    print(x)

[1 2 3 4]
[8 9 6 5]


In [22]:
import numpy as np
ax= np.array([[1,8,5,2,6,8],[7,8,8,9,5,6]])
for x in ax:
    for y in x:
        print(y)

1
8
5
2
6
8
7
8
8
9
5
6


### Iterating 3-D Array
#### In a 2-D array it will go through all the rows.

In [25]:
import numpy as np
ax = np.array([[[1,8,9,6],[6,8,5,2]],[[4,8,5,5],[8,5,2,9]]])
for x in ax : 
    print(x)

[[1 8 9 6]
 [6 8 5 2]]
[[4 8 5 5]
 [8 5 2 9]]


### To return the actual values, the scalars, we have to iterate the arrays in each dimension.

In [26]:
import numpy as np
ax =np.array([[[1,8,9,6],[8,8,8,5]],[[4,8,5,8],[7,4,5,8]]])
for x in ax:
    for y in x:
        for z in y:
            print(z)

1
8
9
6
8
8
8
5
4
8
5
8
7
4
5
8


## Iterating Array Using nditer()

In [28]:
import numpy as np
ax = np.array([[[1,5,8,9],[9,5,9,6]],[[8,5,2,6],[8,8,9,5]]])
for x in np.nditer(ax):
    print(x)

1
5
8
9
9
5
9
6
8
5
2
6
8
8
9
5


In [31]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']): 
  print(x)

# buffered used to convert data into string temporarily , without affecting the original data.
# op_dtypes --- > output data types
    

b'1'
b'2'
b'3'


In [32]:
# another way but in this we permanentily  change the datatype to string
import numpy as np

arr = np.array([1, 2, 3],dtype='S')
for x in np.nditer(arr):
    print(x)


b'1'
b'2'
b'3'


### Iterating with different Step Size

In [35]:
import numpy as np
ax =  np.array([[1,7,8,2],[7,8,8,9]])
for x in np.nditer(ax[:, ::2]): # print every other element from array
    print(x)

1
8
7
8


In [38]:
# another way to do 
import numpy as np
ax =  np.array([[1,7,8,2],[7,8,8,9]])
y=ax[:, ::2]
for x in np.nditer(y): # print every other element from array
    print(x)

1
8
7
8


## Enumerated Iteration Using ndenumerate()

In [44]:
# In 1-D array
import numpy as np 
ax = np.array([8,9,5,2,1,4,7,8,9,5,1])
for idx ,x in np.ndenumerate(ax):
    print(idx,x)

(0,) 8
(1,) 9
(2,) 5
(3,) 2
(4,) 1
(5,) 4
(6,) 7
(7,) 8
(8,) 9
(9,) 5
(10,) 1


In [43]:
# In 2-D array
import numpy as np 
ax = np.array([[1,8,8,5,2,4,5,5],[8,5,2,6,6,2,7,7]])
for idx ,x in np.ndenumerate(ax):
    print(idx,x)

(0, 0) 1
(0, 1) 8
(0, 2) 8
(0, 3) 5
(0, 4) 2
(0, 5) 4
(0, 6) 5
(0, 7) 5
(1, 0) 8
(1, 1) 5
(1, 2) 2
(1, 3) 6
(1, 4) 6
(1, 5) 2
(1, 6) 7
(1, 7) 7


In [46]:
import numpy as np 
ax = np.array([[5,9,5,8,9,5],[8,5,2,1,4,5]])
for x , y in np.ndenumerate(ax):
    print(x,y)



(0, 0) 5
(0, 1) 9
(0, 2) 5
(0, 3) 8
(0, 4) 9
(0, 5) 5
(1, 0) 8
(1, 1) 5
(1, 2) 2
(1, 3) 1
(1, 4) 4
(1, 5) 5
