## Joining Array

In [18]:
# Join two arrays
import numpy as np

ax = np.array([8,9,6,5])
ay = np.array([2,4,9,3])
axx = np.concatenate((ax,ay))
print(axx)

1


In [10]:
# Join two 2-D arrays along rows (axis = 1)
import numpy as np
ar1 = np.array([[8,2,9,6],[8,5,5,1]])
ar2 = np.array([[9,6,2,5],[0,5,2,0]])
arr = np.concatenate((ar1,ar2),axis =)
print(arr)

[[8 2 9 6 9 6 2 5]
 [8 5 5 1 0 5 2 0]]


### Joining array using stack function

In [21]:
import numpy as np
ar1 = np.array([1,2,3])
ar2 = np.array([1,2,3])
arr = np.stack((ar1,ar2),axis=1) 
print(arr)
print(arr.ndim)

[[1 1]
 [2 2]
 [3 3]]
2


### Stacking along rows
hstack()

In [26]:
import numpy as np
ax = np.array([1,2,3])
ay = np.array([8,9,6])
arr = np.hstack((ax,ay))
print(arr)

[1 2 3 8 9 6]


### Stacking along columns
vstack()

In [32]:
import numpy as np
ax = np.array([8,2,3,6])
ay = np.array([6,8,5,4])
arr = np.vstack((ax,ay))
print(arr)

[[8 2 3 6]
 [6 8 5 4]]


### Stacking along height
dstack()

In [34]:
import numpy as np
ax = np.array([1,8,5,6])
ay = np.array([8,9,6,4])
arr=np.dstack((ax,ay))
print(arr)

[[[1 8]
  [8 9]
  [5 6]
  [6 4]]]
