## Random 
#### . Random Data Distribution

#### Generate Random Number 

In [1]:
from numpy import random
x = random.randint(100) # print a random number from 0-100
print(x)

38


#### Generate Random Float

In [2]:
from numpy import random
x = random.rand()
print(x)

0.9488649158513514


#### Generate Random Array

In [3]:
# 1-D Array
from numpy import random
x = random.randint(100, size=(5))
print(x)

[65 83 84 39 19]


In [4]:
# 2-D Array
from numpy import random
x = random.randint(100 , size=(3,5)) # (row,column)

#### Float 
the rand() method also allows you to specify the shape of the array

In [5]:
# 1-D float
from numpy import random
x = random.rand(5)
print(x)

[0.35453976 0.92702914 0.73670158 0.12538408 0.82080842]


In [6]:
# 2-D float
from numpy import random
x = random.rand(4,2)
print(x)

[[0.69428888 0.33692728]
 [0.89412962 0.73801858]
 [0.20271898 0.09315975]
 [0.63467749 0.50803422]]


#### Generate Random Number From Array
choice() randomly returns one of the values from an array.

In [7]:
from numpy import random
x= random.choice([20 ,20 ,24 ,89,3])
print(x)

20


##### size with choice()

In [8]:
from numpy import random
x = random.choice([6,9,4,8,1,5,0] , size=(5,2))
print(x)

[[6 6]
 [6 4]
 [1 0]
 [6 9]
 [0 8]]


##  Random Data Distribution

In [9]:
from numpy import random 
x = random.choice([8,9,5,4],p=[0.2,0.2,0.6,0.0],size =(100))
print(x)


[9 8 8 5 9 5 5 9 5 8 5 5 5 5 8 5 5 8 8 5 5 5 8 9 5 5 5 5 8 5 8 8 5 5 5 5 9
 9 5 5 5 8 5 9 8 5 5 8 5 5 5 5 8 5 9 5 5 8 8 5 8 8 5 9 9 5 8 9 5 5 5 9 5 9
 5 5 5 8 5 5 5 5 5 9 5 5 5 5 5 9 9 5 5 5 8 8 8 5 9 5]


In [10]:
from numpy import random
x= random.choice([0,2,1,5,6,3] , p =[0.1,0.0,0.1,0.2,0.4,0.2], size = (4,6))
print(x)
# in this 2 will not occur in 2-D array

[[6 0 3 3 6 3]
 [0 6 3 6 5 1]
 [3 5 0 1 5 6]
 [5 3 3 0 5 0]]
