## Random Permutation

#### Shuffling Arrays
##### shuffle() makes changes to original array.

In [11]:
from numpy import random
import numpy as np
ar = np.array([1,2,3,4,5,6])
random.shuffle(ar)
print(ar)
print(ar)

[3 4 5 2 6 1]
[3 4 5 2 6 1]


#### Permutation of arrays
##### The permutation() method returns a re-arranged array (and leaves the original array un-changed).



In [8]:
from numpy import random
import numpy as np
ar = np.array([1,2,3,4,5])
print(random.permutation(ar))
print(ar)

[4 1 5 3 2]
[1 2 3 4 5]
