## Searching Arrays
You can search an array for a certain value ,  and return the indexes that get a match.
where()

### Find the indexes where the value is 3


In [3]:
import numpy as np
ax = np.array([1,8,9,3,3,8,5,3,9,3])
arr = np.where(ax == 3)
print(arr)


(array([3, 4, 7, 9], dtype=int64),)


### Find the indexes where the value are even

In [4]:
import numpy as np
ax = np.array([1,8,9,5,8,9,5,9,6,5,6,9,6])
arr = np.where(ax%2 == 0)
print(arr)

(array([ 1,  4,  8, 10, 12], dtype=int64),)


### Find the indexes where the values are odd:

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


### Search Sorted
`numpy.searchsorted` finds the index in a sorted array where a given value (like 6) should be inserted to maintain order.

### Find the indexes where the value 7 should be inserted 

In [11]:
import numpy as np
arr= np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)

1


In [15]:
import numpy as np
arr= np.array([1,3,5,7,9,10,15])
x = np.searchsorted(arr,0,side='right')
print(x)

0


Multiple Values

In [17]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
