In [1]:
import numpy as np
ax = np.array([[1,8,6,3,4],[2,7,9,3,2]])
print(ax.shape) 

(2, 5)


In [2]:
# create an array with 6 dimensions using ndmin 
import numpy as np
ax= np.array([1,2,3,3,4] , ndmin=6)
print(ax.shape)

(1, 1, 1, 1, 1, 5)


## Reshaping
#### NumPy Array Reshaping

#### Reshape from 1-D to 2-D

In [17]:
import numpy as np
ax = np.array([1,3,5,7,9,8,4,6,2,0,2,5,6,3,4,5])
new = ax.reshape([1,8])
new

array([[[1, 3],
        [5, 7],
        [9, 8],
        [4, 6],
        [2, 0],
        [2, 5],
        [6, 3],
        [4, 5]]])

In [18]:
### Reshape 1-D to 2D

In [20]:
import numpy as np
ax = np.array([1,3,5,7,9,8,4,6,2,0,2,5,6,3,4,5])
new = ax.reshape([2,2,4])
new

array([[[1, 3, 5, 7],
        [9, 8, 4, 6]],

       [[2, 0, 2, 5],
        [6, 3, 4, 5]]])

In [34]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(6)

print(newarr)

[1 2 3 4 5 6]


### Returns Copy or View?


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


### Flattening the arrays

In [26]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### Unknown Dimension
#### You are allowed to have one "unknown" dimension.

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


[1.         0.8660254  0.70710678 0.58778525]
