## Sorting Array

In [2]:
# Note: This method returns a copy of the array, leaving the original array unchanged.
import numpy as np
ax = np.array([9,8,4,2,1,5,8,63,5])
print(np.sort(ax))



[ 1  2  4  5  5  8  8  9 63]


#### Sort the array alphabetically

In [4]:
import numpy as np
ax = np.array(['banana','kiwi','mango','grapes'])
print(np.sort(ax))

['banana' 'grapes' 'kiwi' 'mango']


### Sorting a 2-D Array

In [6]:
import numpy as np
ax = np.array([[1,8,9,5,8],[10,5,9,1,8,]])
print(np.sort(ax))

[[ 1  5  8  8  9]
 [ 1  5  8  9 10]]
